//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id_reservacion { get; set; }
        public int id_cliente { get; set; }
        public int id_reservaservicio { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int total { get; set; }
        public string estadoreserva { get; set; }
        public string tipopago { get; set; }
        public string factura { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual reservaServico reservaServico { get; set; }
    }
}
